### ISSUE TITLE
All my lightwave lights are hidden

### ISSUE THREAD

**Issue by robcos** [bigbadblunt/homeassistant-lightwave2#109]
Something has happened to me recently and all my lighwave lights are hidden and the checkbox is disabled.
<img width="485" alt="Screenshot 2023-01-27 at 17 10 25" src="https://user-images.githubusercontent.com/64998/215152646-03146fcb-03d0-457f-b84e-b455acf7a1bd.png">

What can be happening?  I'm not sure when it happened. I noticed very recently because I refreshed the devices in Google home and my lights are gone...

**Comment by bigbadblunt** [comment]
Is it the "hide homekit entities" option?

**Comment by robcos** [comment]
Yes! It's it. When would that be good?

**Comment by bigbadblunt** [comment]
Some users use homekit to control the basic functions (on/off/dim), and only use this integration for the more advanced/obscure function. This is because the homekit connection is more reliable (in relation to keeping the state correctly updated). There was a feature request to hide the entities that are provided by both integrations.
