### ISSUE TITLE
"HomeKit Accessory Protocol"

### ISSUE THREAD

**Issue by MikeLDPT** [bigbadblunt/homeassistant-lightwave2#24]
Hi again,

I have now got your integration working and find that a HA integration for Lightwave Link Plus has also shown itself.  I attach the image below.

I don't know much about HA etc. as yet, and I almost hate to bring this up as this integration may be seen as a rival to yours. But as it has now suddenly shown itself, would it be useful in any way?  I.e. perhaps it complements the functionality of your integration in some way? 

I don't want to install it just because it has appeared, as it may equally interfere with your HACS integration. 

I do not have any Apple or Homekit products apart from this link plus hub. From what I have understood from the [documentation for Homekit Accessory Protocol](https://www.home-assistant.io/integrations/homekit_controller/), it can be added to HA only if it is not already paired with an Apple device via HomeKit.

Have you had a look at it by chance?

![image](https://user-images.githubusercontent.com/70011875/103155330-cd4d6500-4796-11eb-8034-dffbb5336abe.png)

**Comment by bigbadblunt** [comment]
I have no knowledge of homekit. I don't get this option on my install of HA. You should feel free to install it, I'm pretty sure it won't stop my integration from working. If you install it and find it can do thing my integration can't then let me know and I'll look into it.

**Comment by MightyJudge** [comment]
I looked into Homekit support after seeing your questions about it @MikeLDPT.

I only have lightwave light switches and a couple of sockets so I can't comment on how well it works with TRV's etc.

It seems there are pros and cons of using the homekit integration vs this lightwave integration:

Pro:
 - Homekit intergration is a local intergration instead of a cloud one so it works without an internet connection. Particularly useful if you have a flakey internet connection.

Cons:
 - Only the basics are supported - You can't lock switches, control the rgb led on the switch etc
 -  v1 devices aren't supported - I have a v1 socket that controls some desk lights, which doesn't show up (I think this is because it's a v1 device on by v2 hub)

There doesn't appear to be any difference in terms of delay between issuing a command in home assistant and it happening.

I am now using both intergrations, the homekit intergration most of the time (for simple on/off and dimming) but the lightwave integration for a couple of automation I have that involve changing the colour of the leds. 

Running both doesn't seem to have any negative effects - I'm guessing it's make home assistant do a little more behind the scenes though,.

**Comment by MikeLDPT** [comment]
Hi @MightyJudge 

Thanks for looking at this.  You progressed somewhat further than I did.  Being new to HA and all of this I didn't want to confuse myself with multiple options for doing things just yet.  I installed the Homekit version for a short time, and discovered that it didn't support V1, and so deleted it again as BigBadBlunt's integration works well with both Lightwave Connect (V1) and Smart (V2) light switches, which is the extent of what I have, but I only have one set of 2 Gang 2-way switches that are V2 at present.  I am planning on installing more and perhaps upgrading the V1s, but they seem to work pretty well in HA "asis".  It is interesting to learn that the Homekit integration provides local control. May be a bonus as to be honest I chose HA to try to achieve a local private solution.

Thanks
MikeLDPT

**Comment by MikeLDPT** [comment]
Hi @bigbadblunt  

I don't know if you (or anyone) has considered the V1 Mood switches? These are not wired, and are not visible via the integration.  They are used to "remote control" the switches, and I guess may not be entities in the lightwave hub as such.  My research identifies that they are going to be RF 433Mhz devices (as are all V1 products).   Lightwave have not yet achieved the equivalent as a V2 product and I had a thought that the V1 Mood Switch may be re-usable via HA to connect to and control either or both V1 or V2 Lightwave products(?)

If you have mood switches I wonder if you have considered something along the same lines?

I didn't expect it to be so hard to identify a suitable and compatike "off the shelf" RF 433Mhz piece of hardware with decent range (my first stumbling block) for a Raspberry Pi!

It would be interesting to know if you have tried this, or if I may be trying to do something that can't be done.

Thanks

**Comment by bigbadblunt** [comment]
@MightyJudge , thanks for looking into this and documenting it. I think your setup is probably optimal. Hopefully the API gets updated some time to provide the option for everyone (not just HomeKit users) to use local control. There was a user on the HA forums who was told by LightWave the local control was coming, but I'll believe it when I see it.

I'm curious to know what you're using the LEDs for if you're willing to share.
